services:
  postgres:
    image: postgres
    container_name: PoopAppDB
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./database/database-connection.json:/pgadmin4/servers.json

